<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiseasesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('diseases')->insert([

            //diseases
            [
                'name' => 'Influenza (Flu)',
                'symptoms' => 'Fever or feeling feverish/chills, Cough, Sore throat, Runny or stuffy nose, Muscle or body aches, Headaches, Fatigue (tiredness)',
                'prevention' => 'The best way to prevent flu is by getting vaccinated each year. Everyone 6 months of age and older should get a flu vaccine every season. Vaccination is particularly important for people who are at high risk of serious complications from influenza. Flu vaccines cause antibodies to develop in the body about two weeks after vaccination. These antibodies provide protection against infection with the viruses that are used to make the vaccine. The seasonal flu vaccine protects against the influenza viruses that research indicates will be most common during the upcoming season. Traditional flu vaccines (called “trivalent” vaccines) are made to protect against three flu viruses; an influenza A (H1N1) virus, an influenza A (H3N2) virus, and an influenza B virus. There are also flu vaccines made to protect against four flu viruses (called “quadrivalent” vaccines).',
                'treatment' => 'Antiviral drugs can treat flu illness. CDC recommends prompt treatment for people who have flu infection or suspected flu infection and who are at high risk of serious flu complications, such as people with asthma, diabetes (including gestational diabetes), or heart disease. Other people also may be treated with antiviral drugs by their doctor this season. Most people who get flu will recover in a few days to less than two weeks, but some people will develop complications (such as pneumonia) as a result of flu, some of which can be life-threatening and result in death.',
                'description' => 'Influenza (flu) is a contagious respiratory illness caused by influenza viruses. It can cause mild to severe illness. Serious outcomes of flu infection can result in hospitalization or death. Some people, such as older people, young children, and people with certain health conditions, are at high risk of serious flu complications. There are two main types of influenza (flu) virus: Types A and B. The influenza A and B viruses that routinely spread in people (human influenza viruses) are responsible for seasonal flu epidemics each year. Influenza A viruses can be broken down into sub-types depending on the genes that make up the surface proteins. Over the course of a flu season, different types (A & B) and subtypes (influenza A) of influenza circulate and cause illness. Influenza viruses are constantly changing, so they may cause illness several times throughout a person’s lifetime. The timing of flu is very unpredictable and can vary from season to season. Flu activity most commonly peaks in the U.S. between December and February. However, seasonal flu activity can begin as early as October and continue to occur as late as May. Flu activity has been elevated since November and is expected to continue for several weeks. CDC recommends that people get a flu vaccine by the end of October, if possible. Getting vaccinated later, however, can still be beneficial and vaccination should continue to be offered throughout the flu season, even into January or later.',
            ],

            [
                'name' => 'COVID-19',
                'symptoms' => 'Fever or chills, Cough, Shortness of breath or difficulty breathing, Fatigue, Muscle or body aches, Headache, New loss of taste or smell, Sore throat, Congestion or runny nose, Nausea or vomiting, Diarrhea',
                'prevention' => 'The best way to prevent illness is to avoid being exposed to this virus. You can take steps to slow the spread. Maintain good social distance (about 6 feet). This is very important in preventing the spread of COVID-19. Wash your hands often with soap and water. If soap and water are not available, use a hand sanitizer that contains at least 60% alcohol. Avoid touching your eyes, nose, and mouth with unwashed hands. Avoid close contact with people who are sick, even inside your home. If you are sick, to keep from spreading respiratory illness to others, you should stay home. Cover your mouth and nose with a cloth face cover when around others. Cover your coughs and sneezes. Clean and disinfect frequently touched surfaces daily. This includes tables, doorknobs, light switches, countertops, handles, desks, phones, keyboards, toilets, faucets, and sinks. If surfaces are dirty, clean them. Use detergent or soap and water prior to disinfection.',
                'treatment' => 'If you have a fever, cough or other symptoms, you might have COVID-19. Most people have mild illness and are able to recover at home. If you think you may have been exposed to COVID-19, contact your healthcare provider. Keep track of your symptoms. If you have an emergency warning sign (including trouble breathing), get emergency medical care immediately. If you have a medical emergency and need to call 911, notify the operator that you have or think you might have, COVID-19. If possible, put on a cloth face covering before medical help arrives.',
                'description' => 'Coronavirus disease 2019 (COVID-19) is a respiratory illness that can spread from person to person. The virus that causes COVID-19 is a novel coronavirus that was first identified during an investigation into an outbreak in Wuhan, China. The virus that causes COVID-19 is thought to spread mainly from person to person, mainly through respiratory droplets produced when an infected person coughs, sneezes, or talks. These droplets can land in the mouths or noses of people who are nearby or possibly be inhaled into the lungs. Spread is more likely when people are in close contact with one another (within about 6 feet). COVID-19 seems to be spreading easily and sustainably in the community (“community spread”) in many affected geographic areas. Community spread means people have been infected with the virus in an area, including some who are not sure how or where they became infected.',
            ],

            [
                'name' => 'Measles',
                'symptoms' => 'Fever, Dry cough, Runny nose, Sore throat, Inflamed eyes (conjunctivitis), Tiny white spots with bluish-white centers on a red background found inside the mouth on the inner lining of the cheek — also called Koplik\'s spots, A skin rash made up of large, flat blotches that often flow into one another',
                'prevention' => 'The best protection against measles is measles-mumps-rubella (MMR) vaccine. MMR vaccine provides long-lasting protection against all strains of measles. Your child needs two doses of MMR vaccine for best protection: The first dose at 12 through 15 months of age, The second dose 4 through 6 years of age. Teens and adults should also be up to date on their MMR vaccination.',
                'treatment' => 'There is no specific antiviral treatment for measles. Medical care is focused on relieving symptoms and includes rest, fluids, and fever-reducing medication. Antibiotics are not effective against measles, as it is a viral illness. However, antibiotics may be prescribed if the patient develops a secondary bacterial infection such as an ear infection or pneumonia.',
                'description' => 'Measles is a highly contagious virus that lives in the nose and throat mucus of an infected person. It can spread to others through coughing and sneezing. Also, measles virus can live for up to two hours in an airspace where the infected person coughed or sneezed. If other people breathe the contaminated air or touch the infected surface, then touch their eyes, noses, or mouths, they can become infected. Measles is so contagious that if one person has it, up to 90% of the people close to that person who are not immune will also become infected. Infected people can spread measles to others from four days before through four days after the rash appears. Measles is a disease of humans; measles virus is not spread by any other animal species. Measles is a very contagious disease caused by a virus. It spreads through the air when an infected person coughs or sneezes. Measles starts with fever. Soon after, it causes a cough, runny nose, and red eyes. Then a rash of tiny, red spots breaks out. It starts at the head and spreads to the rest of the body. Measles can be prevented with MMR vaccine. The vaccine protects against three diseases: measles, mumps, and rubella. CDC recommends children get two doses of MMR vaccine, starting with the first dose at 12 through 15 months of age, and the second dose at 4 through 6 years of age. Teens and adults should also be up to date on their MMR vaccination.',
            ],

            [
                'name' => 'Polio (Poliomyelitis)',
                'symptoms' => 'Initial symptoms of polio include fever, fatigue, headache, vomiting, stiffness in the neck, and pain in the limbs. In a small proportion of cases, the disease causes paralysis, which is often permanent. There is no cure for polio, it can only be prevented by immunization.',
                'prevention' => 'Polio vaccine, given multiple times, can protect a child for life. The vaccine protects a child by preparing their body to fight the polio virus. Almost all children (99 children out of 100) who get all the recommended doses of vaccine will be protected from polio.',
                'treatment' => 'There is no cure for polio, it can only be prevented by immunization. Polio vaccine, given multiple times, can protect a child for life. The vaccine protects a child by preparing their body to fight the polio virus. Almost all children (99 children out of 100) who get all the recommended doses of vaccine will be protected from polio.',
                'description' => 'Polio is a crippling and potentially deadly infectious disease caused by a virus that invades the brain and spinal cord, causing paralysis. When you first get polio, you may feel like you have the flu. You might have a fever, sore throat, cough, headache, stomach pain, and vomiting. These symptoms usually go away in 2 to 5 days. The virus lives in an infected person’s throat and intestines. It spreads through contact with poop. You can get it if you: Touch poop that has the virus on it and then touch your mouth, Eat food or drink liquids that have the virus in them, Touch objects that have the virus on them and then touch your mouth, nose, or eyes, Have close contact with someone who has the virus — for example, by kissing the person or caring for the person when they’re sick. You can pass the virus to others for weeks. Up to 72% of people with polio don’t have any symptoms, so they may not know they’re infected. But they can still spread the virus to others.',
            ],

            [
                'name' => 'Tetanus',
                'symptoms' => 'Tetanus symptoms include: Jaw cramping, Sudden, involuntary muscle tightening (muscle spasms) – often in the stomach, Painful muscle stiffness all over the body, Trouble swallowing, Jerking or staring (seizures), Headache, Fever and sweating, Changes in blood pressure and fast heart rate',
                'prevention' => 'The best way to prevent tetanus is to get vaccinated. Doctors recommend that all children get the DTaP vaccine. Doctors recommend that preteens get a booster shot called Tdap at age 11 or 12. People should get a tetanus booster shot every 10 years. If you get a bad cut or burn, see your doctor. You may need a tetanus shot if you have not had one in the last 5 years.',
                'treatment' => 'Tetanus is treated with antibiotics, muscle relaxants, and a tetanus vaccine. A booster shot of the tetanus vaccine is given to the patient. The wound is cleaned and bandaged. If the wound is deep, a tetanus antitoxin may also be given.',
                'description' => 'Tetanus is a serious bacterial infection that affects the nervous system and causes muscles throughout the body to tighten. It’s also called lockjaw because the infection often causes muscle contractions in the jaw and neck. However, it can eventually spread to other parts of the body. Tetanus can interfere with your ability to breathe and, ultimately, threaten your life. Tetanus is commonly known as “lockjaw.” Thanks to its widespread use, lockjaw is now relatively rare in the United States. Only about 30 reported cases of tetanus are seen in the U.S. each year. However, it remains a significant problem in developing countries that don’t have access to the tetanus vaccine. The bacteria that cause tetanus can be found in soil, dust, and feces. When they enter a deep flesh wound, they multiply and produce toxins that interfere with muscle relaxation and cause severe muscle spasms. These spasms can be so powerful that they tear muscle fibers or even cause spine fractures.',
            ],

            [
                'name' => 'Diphtheria',
                'symptoms' => 'A thick, gray membrane covering your throat and tonsils, A sore throat and hoarseness, Swollen glands (enlarged lymph nodes) in your neck, Difficulty breathing or rapid breathing, Nasal discharge, Fever and chills, Malaise, Swollen glands (enlarged lymph nodes) in your neck, Difficulty breathing or rapid breathing, Nasal discharge, Fever and chills, Malaise',
                'prevention' => 'The best way to prevent diphtheria is to get vaccinated. Doctors recommend that all children get the DTaP vaccine. Doctors recommend that preteens get a booster shot called Tdap at age 11 or 12. People should get a tetanus booster shot every 10 years. If you get a bad cut or burn, see your doctor. You may need a tetanus shot if you have not had one in the last 5 years.',
                'treatment' => 'Diphtheria is treated with antitoxins and antibiotics. The antitoxins neutralize the toxins produced by the bacteria. The antibiotics kill the bacteria. The wound is cleaned and bandaged. If the wound is deep, a tetanus antitoxin may also be given.',
                'description' => 'Diphtheria is a serious bacterial infection. You can catch it from a person who has the infection and coughs or sneezes. You can also get infected by coming in contact with an object, such as a toy, that has bacteria on it. Diphtheria usually affects the nose and throat. Symptoms include: A thick covering in the back of the throat, A sore throat and hoarseness, Swollen glands (enlarged lymph nodes) in your neck, Difficulty breathing or rapid breathing, Nasal discharge, Fever and chills, Malaise. Diphtheria can lead to breathing problems, paralysis, heart failure, and even death. If your child has this infection, call your doctor. Diphtheria is treated with antibiotics. Vaccines can prevent diphtheria.',
            ],

            [
                'name' => 'Hepatitis B',
                'symptoms' => 'Abdominal pain, Dark urine, Fever, Joint pain, Loss of appetite, Nausea and vomiting, Weakness and fatigue, Yellowing of your skin and the whites of your eyes (jaundice)',
                'prevention' => 'Hepatitis B vaccination',
                'treatment' => 'Acute hepatitis B infection doesn\'t require treatment. If you develop chronic hepatitis B, you may need treatment with antiviral medications. Antiviral medications can\'t cure hepatitis B, but they can help control the virus so that it doesn\'t damage your liver. Antiviral medications are taken orally. Chronic hepatitis B infection may eventually cause severe liver damage and liver cancer. If you have chronic hepatitis B, your doctor may recommend antiviral medications to reduce the risk of liver cancer. If your liver has been severely damaged, a liver transplant may be an option.',
                'description' => 'Hepatitis B is a serious liver infection caused by the hepatitis B virus (HBV). For some people, hepatitis B infection becomes chronic, meaning it lasts more than six months. Having chronic hepatitis B increases your risk of developing liver failure, liver cancer or cirrhosis — a condition that permanently scars of the liver. Most people infected with hepatitis B as adults recover fully, even if their signs and symptoms are severe. Infants and children are more likely to develop a chronic hepatitis B infection. A vaccine can prevent hepatitis B, but there\'s no cure if you have it. If you\'re infected, taking certain precautions can help prevent spreading HBV to others.',
            ],

            [
                'name' => 'Hepatitis A',
                'symptoms' => 'Fatigue, Sudden nausea and vomiting, Abdominal pain or discomfort, especially on the upper right side beneath your lower ribs (by your liver), Clay-colored bowel movements, Loss of appetite, Low-grade fever, Dark urine, Joint pain, Yellowing of the skin and the whites of your eyes (jaundice)',
                'prevention' => 'Hepatitis A vaccination',
                'treatment' => 'There\'s no specific treatment for hepatitis A. But symptoms of acute hepatitis A infection can be treated, and most people with hepatitis A eventually recover completely with no permanent liver damage. Treatment mainly involves relieving symptoms. Your doctor may recommend: Rest. Many people with hepatitis A infection feel tired and sick and have less energy. You may need to take a break from your normal daily activities until your energy levels return to normal. Adequate nutrition. If you\'re nauseated, you may not feel like eating. However, it\'s important to get adequate nutrition. Until your appetite returns, your doctor may recommend a special diet to help promote healing and restore proper liver function. Follow your doctor\'s instructions regarding diet.',
                'description' => 'Hepatitis A is a highly contagious liver infection caused by the hepatitis A virus. The virus is one of several types of hepatitis viruses that cause inflammation and affect your liver\'s ability to function. You\'re most likely to get hepatitis A from contaminated food or water or from close contact with a person or object that\'s infected. Mild cases of hepatitis A don\'t require treatment. Most people who are infected recover completely with no permanent liver damage. Practicing good hygiene, including washing hands frequently, is one of the best ways to protect against hepatitis A. Vaccines are available for people most at risk.',
            ],

            [
                'name' => 'Varicella (Chickenpox)',
                'symptoms' => 'Fever, Loss of appetite, Headache, Tiredness and a general feeling of being unwell (malaise), A skin rash made up of blister-like lesions, which first appear on the face and trunk, and then spread throughout the body, Itching',
                'prevention' => 'Chickenpox vaccine',
                'treatment' => 'Chickenpox is usually mild and runs its course in five to 10 days, but it can cause more serious problems when teens and adults get it. People who have weakened immune systems or other medical problems may have complications from chickenpox. They may get pneumonia or, rarely, an inflammation of the brain (encephalitis). They may need to be treated in the hospital. If you have chickenpox, you can help prevent spreading the virus to others by staying home until all blisters scab over. If you\'re at high risk of complications from chickenpox — for example, you\'re pregnant, you have a weakened immune system or you\'re an adult — your doctor may prescribe an antiviral medication. Antiviral drugs lessen the severity of chickenpox and may prevent complications. They work best if given within the first 24 hours after the rash appears. Acetaminophen (Tylenol, others) can help relieve pain and fever. Never give aspirin to children with chickenpox. It may lead to Reye\'s syndrome, a rare but life-threatening condition.',
                'description' => 'Chickenpox is a highly contagious disease caused by the varicella-zoster virus (VZV). It can cause an itchy, blister-like rash. The rash first appears on the chest, back, and face, and then spreads over the entire body, causing between 250 and 500 itchy blisters. Chickenpox can be serious, especially in babies, adults, and people with weakened immune systems. It spreads easily from infected people to others who have never had chickenpox or received the chickenpox vaccine. Chickenpox spreads in the air through coughing or sneezing. It can also be spread by touching or breathing in the virus particles that come from chickenpox blisters. A person with chickenpox can spread the disease from 1 to 2 days before they get the rash until all their chickenpox blisters have formed scabs. This usually happens within 5 to 7 days of the rash appearing.',
            ],

            [
                'name' => 'Human Papillomavirus (HPV)',
                'symptoms' => 'Fever, Cough, Shortness of breath, Chest pain, Stiff neck, Confusion, Disorientation, Sensitivity to light, Joint pain, Chills',
                'prevention' => 'Pneumococcal vaccination',
                'treatment' => 'Pneumococcal pneumonia can be treated with antibiotics. However, many types of pneumococcal bacteria have become resistant to some of the antibiotics used to treat these infections. Vaccines are available to prevent pneumococcal pneumonia and the flu. Other preventive measures include washing your hands frequently and not smoking.',
                'description' => 'Pneumococcal disease is an infection caused by Streptococcus pneumoniae bacteria (“pneumococcus”). These bacteria can cause many types of illnesses, including: Pneumococcal pneumonia, which affects the lungs, Pneumococcal bacteremia, which affects the blood, Pneumococcal meningitis, which affects the coverings of the brain and spinal cord. Pneumococcal disease is common in young children, but older adults are at greatest risk of serious pneumococcal infections and even death. There are two vaccines that help protect against pneumococcal disease: PCV13 and PPSV23. Talk to your or your child’s doctor to find out which pneumococcal vaccines are recommended for you or your child.',
            ],

            [
                'name' => 'Pneumococcal Disease',
                'symptoms' => 'Fever, Cough, Shortness of breath, Chest pain, Stiff neck, Confusion, Disorientation, Sensitivity to light, Joint pain, Chills',
                'prevention' => 'Pneumococcal vaccination',
                'treatment' => 'Pneumococcal pneumonia can be treated with antibiotics. However, many types of pneumococcal bacteria have become resistant to some of the antibiotics used to treat these infections. Vaccines are available to prevent pneumococcal pneumonia and the flu. Other preventive measures include washing your hands frequently and not smoking.',
                'description' => 'Pneumococcal disease is an infection caused by Streptococcus pneumoniae bacteria (“pneumococcus”). These bacteria can cause many types of illnesses, including: Pneumococcal pneumonia, which affects the lungs, Pneumococcal bacteremia, which affects the blood, Pneumococcal meningitis, which affects the coverings of the brain and spinal cord. Pneumococcal disease is common in young children, but older adults are at greatest risk of serious pneumococcal infections and even death. There are two vaccines that help protect against pneumococcal disease: PCV13 and PPSV23. Talk to your or your child’s doctor to find out which pneumococcal vaccines are recommended for you or your child.',
            ],

            [
                'name' => 'Meningococcal Disease',
                'symptoms' => ' Fever, Headache, Stiff neck, Nausea, Vomiting, Increased sensitivity to light (photophobia), Altered mental status (confusion)',
                'prevention' => 'Meningococcal vaccination',
                'treatment' => 'Meningococcal meningitis is treated with antibiotics. It is very important that treatment be started as soon as possible. If your doctor suspects that you have meningitis, he or she may start antibiotics even before doing tests. This may help prevent serious complications, such as brain damage or hearing loss. If you have meningococcal meningitis, your doctor may also want to give antibiotics to people you have had close contact with, such as family members and roommates. This is to prevent them from getting the disease.',
                'description' => 'Meningococcal disease is a serious bacterial illness. It is a leading cause of bacterial meningitis in children 2 through 18 years old in the United States. Meningitis is an infection of the covering of the brain and the spinal cord. Meningococcal disease also causes blood infections. About 1,000–1,200 people get meningococcal disease each year in the U.S. Even when they are treated with antibiotics, 10-15% of these people die. Of those who live, another 11-19% lose their arms or legs, become deaf, have problems with their nervous systems, become mentally retarded, or suffer seizures or strokes. Anyone can get meningococcal disease. But it is most common in infants less than one year of age and people with certain medical conditions, such as lack of a spleen. College freshmen who live in dormitories and military recruits also have an increased risk of getting meningococcal disease.',
            ],

            
        ]);
    }
}
